In [12]:
def func(variables = ['x','y'],f = 'x**2 - x*y + y**2 + 9*x - 6 * y + 20'):
    for i in range(len(variables)):
        f = f.replace(variables[i],f'x[{i}]')
    return f
func()

'x[0]**2 - x[0]*x[1] + x[1]**2 + 9*x[0] - 6 * x[1] + 20'

In [13]:
def gradFunc(var1 = 'x',var2 = 'y', f = 'x**2 - x*y + y**2 + 9*x - 6 * y + 20' ):
    x = Symbol(var1)
    y = Symbol(var2)
    f = parse_expr(f)
    return [str(f.diff(x)).replace('x','x[0]').replace('y','x[1]') , str(f.diff(y)).replace('x','x[0]').replace('y','x[1]')]
gradFunc()

['2*x[0] - x[1] + 9', '-x[0] + 2*x[1] - 6']

In [14]:
# задаем вручную с помощью функций сверху
def f(x):
    return x[0]**2 - x[0]*x[1] + x[1]**2 + 9*x[0] - 6 * x[1] + 20

# gradient
def g(x):
    return np.array([2*x[0] - x[1] + 9, -x[0] + 2*x[1] - 6])

In [15]:
from sympy.parsing.sympy_parser import parse_expr
from sympy import Symbol
import numpy as np
import time

In [16]:
def gradient_const_step(func = f, grad = g, nvar = 2, h = 0.001, maxk = 500, eps = 0.00001, unusualx0 = False):
    start_time = time.time()
    if unusualx0 :
        xk = np.array([10]) * nvar
    else :
        xk = np.array([0]) * nvar # столько 0, сколько переменных
    try:
        gk = g(xk)
    except ZeroDivisionError:
        xk += 100
        gk = g(xk)
    fk = f(xk)
    k = 0
    while sum(gk**2)**(1/2) > eps and k < maxk:
        k += 1
        xk = xk - h * gk
        gk = g(xk)
        fk = f(xk)
    if k == maxk :
        print(f'время выполнения( в секундах ) = {(time.time() - start_time)}')
        return (xk, fk, 1)
    elif k == 0 :
        print(f'время выполнения( в секундах ) = {(time.time() - start_time)}')
        return (xk, fk, 2)
    else:
        print(f'время выполнения( в секундах ) = {(time.time() - start_time)}')
        return(xk,fk,0)

In [17]:
def gradient_changing_step(func = f, grad = g, nvar = 2,sigm = 0.5, h = 0.001, maxk = 500, eps = 0.00001, unusualx0 = False):
    if not (0 < sigm < 1) :
        return('Ошибка ввода параметра дробления')
    start_time = time.time()
    if unusualx0 :
        xk = np.array([10]) * nvar
    else :
        xk = np.array([0]) * nvar # столько 0, сколько переменных
    try:
        gk = g(xk)
    except ZeroDivisionError:
        xk += 100
        gk = g(xk)
    fk = f(xk)
    k = 0
    while sum(gk**2)**(1/2) > eps and k < maxk:
        k += 1
        xj = xk # x(k-1)
        xk = xk - h * gk
        fk = f(xk)
        if fk > f(xj):
            h /= sigm
        gk = g(xk)
        
    if k == maxk :
        print(f'время выполнения( в секундах ) = {(time.time() - start_time)}')
        return (xk, fk, 1)
    elif k == 0 :
        print(f'время выполнения( в секундах ) = {(time.time() - start_time)}')
        return (xk, fk, 2)
    else:
        print(f'время выполнения( в секундах ) = {(time.time() - start_time)}')
        return(xk,fk,0)

## можно попробовать разные значения параметров, резульаты изменятся, сейчас часто достигается макс итераций,
## т.к. eps маленькое, а макск = 500
## чтобы сойтись все таки - увеличить макск или подправить другие параметры ??

In [151]:
## Тестирование 1) 10*x1**2+3*x2**2+2*x1*x2-6

In [152]:
func(variables = ['x1','x2'],f = '10*x1**2+3*x2**2+2*x1*x2-6')

'10*x[0]**2+3*x[1]**2+2*x[0]*x[1]-6'

In [153]:
gradFunc(var1 = 'x1',var2 = 'x2',f = '10*x1**2+3*x2**2+2*x1*x2-6')

['20*x[0] + 2*x[1]', '2*x[0] + 6*x[1]']

In [154]:
# задаем вручную с помощью функций сверху
def f(x):
    return 10*x[0]**2+3*x[1]**2+2*x[0]*x[1]-6

# gradient
def g(x):
    return np.array([20*x[0] + 2*x[1], 2*x[0] + 6*x[1]])

In [155]:
gradient_const_step()

время выполнения( в секундах ) = 0.0


([0, 0], -6, 2)

In [156]:
gradient_changing_step()

время выполнения( в секундах ) = 0.0


([0, 0], -6, 2)

In [82]:
## Тестирование 2) x1***3+2*x2**2-3*x1-4*x2

In [157]:
func(variables = ['x1','x2'],f = 'x1**3+2*x2**2-3*x1-4*x2')

'x[0]**3+2*x[1]**2-3*x[0]-4*x[1]'

In [158]:
gradFunc(var1 = 'x1',var2 = 'x2',f = 'x1**3+2*x2**2-3*x1-4*x2')

['3*x[0]**2 - 3', '4*x[1] - 4']

In [159]:
# задаем вручную с помощью функций сверху
def f(x):
    return x[0]**3+2*x[1]**2-3*x[0]-4*x[1]

# gradient
def g(x):
    return np.array([3*x[0]**2 - 3, 4*x[1] - 4])

In [160]:
gradient_const_step()

время выполнения( в секундах ) = 0.0049860477447509766


(array([0.90561226, 0.86520642]), -3.937775151514923, 1)

In [161]:
gradient_changing_step()

время выполнения( в секундах ) = 0.0069425106048583984


(array([0.90561226, 0.86520642]), -3.937775151514923, 1)

In [162]:
## Тестирование 3) x1**2+2*x2**2+exp(x1+x2)

In [163]:
func(variables = ['x1','x2'],f = 'x1**2+2*x2**2+exp(x1+x2)')

'x[0]**2+2*x[1]**2+exp(x[0]+x[1])'

In [164]:
gradFunc(var1 = 'x1',var2 = 'x2',f = 'x1**2+2*x2**2+exp(x1+x2)')

['2*x[0] + exp(x[0] + x[1])', '4*x[1] + exp(x[0] + x[1])']

In [165]:
# задаем вручную с помощью функций сверху
def f(x):
    return x[0]**2+2*x[1]**2+exp(x[0]+x[1])

# gradient
def g(x):
    return np.array([2*x[0] + exp(x[0] + x[1]), 4*x[1] + exp(x[0] + x[1])])

In [166]:
from math import exp

In [169]:
gradient_const_step(maxk = 5000)

время выполнения( в секундах ) = 0.04789876937866211


(array([-0.31276288, -0.15638453]), 0.7722682277438524, 0)

In [170]:
gradient_changing_step(maxk = 5000)

время выполнения( в секундах ) = 0.05684661865234375


(array([-0.31276288, -0.15638453]), 0.7722682277438524, 0)

In [85]:
## Тестирование 4) (x-2)**2+(x-3)**2

In [171]:
func(variables = ['x'],f = '(x-2)**2+(x-3)**2')

'(x[0]-2)**2+(x[0]-3)**2'

In [172]:
gradFunc(var1 = 'x',f = '(x-2)**2+(x-3)**2')

['4*x[0] - 10', '0']

In [173]:
# задаем вручную с помощью функций сверху
def f(x):
    return (x[0]-2)**2+(x[0]-3)**2

# gradient
def g(x):
    return np.array([4*x[0] - 10])

In [176]:
gradient_const_step(nvar = 1, maxk = 10000)

время выполнения( в секундах ) = 0.02892589569091797


(array([2.4999975]), 0.5000000000124966, 0)

In [177]:
gradient_changing_step(nvar = 1, maxk = 10000)

время выполнения( в секундах ) = 0.03391599655151367


(array([2.4999975]), 0.5000000000124966, 0)

In [86]:
## Тестирование 5) 4*x+cos(x)

In [178]:
func(variables = ['x'],f = '4*x+cos(x)')

'4*x[0]+cos(x[0])'

In [179]:
gradFunc(var1 = 'x',f = '4*x+cos(x)')

['4 - sin(x[0])', '0']

In [180]:
from math import sin, cos

In [181]:
# задаем вручную с помощью функций сверху
def f(x):
    return 4*x[0]+cos(x[0])

# gradient
def g(x):
    return np.array([4 - sin(x[0])])

In [ ]:
# не сходится, мб нужно ещё больше шагов, т.к достигается лимит

In [185]:
gradient_const_step(nvar = 1, maxk = 1000000)

время выполнения( в секундах ) = 6.452968597412109


(array([-3873.48449406]), -15494.933055234365, 1)

In [187]:
gradient_changing_step(nvar = 1, maxk = 1000000)

время выполнения( в секундах ) = 7.842103958129883


(array([-3873.48449406]), -15494.933055234365, 1)

In [87]:
## Тестирование 6) ln(x**2)

In [188]:
func(variables = ['x'],f = 'ln(x**2)')

'ln(x[0]**2)'

In [189]:
gradFunc(var1 = 'x',f = 'ln(x**2)')

['2/x[0]', '0']

In [195]:
# задаем вручную с помощью функций сверху
def f(x):
    return log(x[0]**2)

# gradient
def g(x):
    return np.array([2/x[0]])

In [194]:
from math import log

In [ ]:
## не сходится

In [215]:
gradient_const_step(nvar = 1, unusualx0 = True, maxk = 50000)

время выполнения( в секундах ) = 0.32416367530822754


(array([-1.65414315]), 1.006566281836148, 1)

In [216]:
gradient_changing_step(nvar = 1, unusualx0 = True, maxk = 50000)

время выполнения( в секундах ) = 0.3652305603027344


(array([-157.93923521]), 10.124420743514705, 1)

In [18]:
## Тестирование 7) 4*x+x**2+(200-x)**2

In [19]:
func(variables = ['x'],f = '4*x+x**2+(200-x)**2' )

'4*x[0]+x[0]**2+(200-x[0])**2'

In [20]:
gradFunc(var1 = 'x',f = '4*x+x**2+(200-x)**2')

['4*x[0] - 396', '0']

In [21]:
# задаем вручную с помощью функций сверху
def f(x):
    return 4*x[0]+x[0]**2+(200-x[0])**2

# gradient
def g(x):
    return np.array([4*x[0] - 396])

In [23]:
gradient_const_step(nvar = 1, maxk = 10000)

время выполнения( в секундах ) = 0.03290390968322754


(array([98.9999975]), 20398.000000000015, 0)

In [24]:
gradient_changing_step(nvar = 1, maxk = 10000)

время выполнения( в секундах ) = 0.04188108444213867


(array([98.99999752]), 20398.000000000015, 0)